version: '3.7'

services:
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        volumes:
            - './server:/server'
            - '/server/node_modules'
        ports:
            - '3001:8888'
        environment:
            - NODE_ENV=development
        stdin_open: true

    controller: controller
