version: '3.7'
services:
    time_machine: 
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - '.:/app'
            - '/app/node_modules'
        ports:
            - '8888:8888'
        environment:
            - NODE_ENV=development
        stdin_open: true